build:
  environment:
    php:
      version: 8.2

  dependencies:
    before:
      - composer install --no-interaction --prefer-dist

  tests:
    override:
      - php-scrutinizer-run

checks:
  php: true

filter:
  excluded_paths:
    - vendor/*