build:
    environment:
        php:
            version: 8.2

    cache:
        directories:
            - vendor
            - ~/.composer/cache

    dependencies:
        before:
            - composer self-update --2
            - composer install --no-interaction --prefer-dist

    tests:
        override:
            -
                command: vendor/bin/phpunit --coverage-clover=coverage.xml
                coverage:
                    file: coverage.xml
                    format: clover

            -
                command: vendor/bin/phpcs --standard=PSR12 src/

checks:
    php:
        code_rating: true
        duplication: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

filter:
    excluded_paths:
        - vendor/*
        - tests/*